apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-poc
data:
  application.properties: |
    welcome.message=Hello from kubernetes propety source default 
    message=Hi from kubernetes Aparna
    welcome.message1=hello from configmap 1
    welcome.default=default message
  application-dev.properties: |
    welcome.message1=Hello from kubernetes propety source from DEV 
  application-prod.properties: |
    spring.profiles=prod
    welcome.message1=Hello from kubernetes propety source from PROD 