apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-poc
data:
  application.yml: |-
    welcome:
      message: Hello from kubernetes propety source from default message
    welcome:
      message1: Hello from kubernetes propety source from default message1
    ---
    spring:
      profiles: dev
    welcome:
      message1: Hello from kubernetes propety source from DEV
    ---
    spring:
      profiles: prod
    welcome:
      message1: Hello from kubernetes propety source from PROD
