apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-poc
data:
  application.properties: |-
    welcome.message=Hello from kubernetes propety source default 
    message=Hi from kubernetes Aparna
    welcome.message1=hello from configmap 1
    welcome.default=default message
    ---
    spring.profiles=dev
    welcome.message1=Hello from kubernetes propety source from DEV 
    ---
    spring.profiles=prod
    welcome.message1=Hello from kubernetes propety source from PROD 