apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-poc
data:
  application.properties: |-
    welcome.message=Hello from kubernetes Aparna
    message=Hi from kubernetes Aparna
    welcome.message1=hello from configmap 1